website/auth.py
from flask import ( 
    Blueprint, flash, render_template, request, url_for, redirect
) 
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user,login_required,logout_user, current_user, AnonymousUserMixin
from . import db
from functools import wraps

#Defining the blueprint
bp = Blueprint('auth', __name__ )

def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        #check if user is authenticated, if not redirect to home page and flash warning
        if current_user.is_authenticated:
            return f(*args, **kwargs)
        else:
            flash("You must be logged in to view this page.", 'danger')
            return redirect('/')
    return wrap


@bp.route('/login', methods=['GET','POST'])
def login():
    login_form = LoginForm()
    error=None
    if login_form.validate_on_submit():
        user_name = login_form.username.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        #if there is no user with that name
        if u1 is None:
            error='Incorrect user name or password'
        #check the password - notice password hash function
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect user name or password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            flash(error, 'danger')

    return render_template('user.html', form=login_form,  heading='Login')

@bp.route('/register', methods=['GET','POST'])
def register():
    register = RegisterForm()
    #the validation of form submis is fine
    if (register.validate_on_submit() == True):
            #get username, password, contact number, address and email from the form
            uname =register.name.data
            pwd = register.password.data
            email=register.email.data
            area_of_expertise = register.area_of_expertise.data
            gender = register.gender.data
            birthdate = register.birthdate.data
            #check if a user exists
            u1 = User.query.filter_by(name=uname).first()
            if u1:
                flash('User name already exists, please login', 'danger')
                return redirect(url_for('auth.login'))
            # don't store the password - create password hash
            pwd_hash = generate_password_hash(pwd)
            #create a new user model object
            new_user = User(name=uname, password_hash=pwd_hash, email=email, area_of_expertise = area_of_expertise, gender= gender, birthdate = birthdate)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            flash("New account created!", 'success')
            return redirect(url_for('main.index'))
    #the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')


@bp.route('/logout')
@login_required
#Allows logged in user to log out and redirects to home page
def logout():
    logout_user()
    return redirect('/')

website/templates/about.html
<!-- Creating the about page-->
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="px-4 py-0 mt-5 text-center">
      <h1 class="display-5 fw-bold">Our Goal</h1>
      <div class="col-lg-6 mx-auto row justify-content-center">
        <p class="lead mb-2 pb-5">With this simple website, we hope to educate people about the biases within applicant tracking systems and how they can combat and overcome them.</p>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette align-items-center mb-4">
      <div class="col-md-6">
      <h2 class="featurette-heading">Applicant Tracking Systems. <span   class="text-muted">Automated tracking and rating of employee prospects.</span></h2>
      <p class="lead">Studies have shown that over 75% of employers use some form of software for the resume and applicant tracking. These softwares read through resumes looking for key words or phrases to identify worthy hires.</p>
      </div>
      <div class="col-md-6">
       <img class ="img-thumbnail" src=static/images/resume_img.jpeg alt="Resume" width="600" height="400">
      </div>
     </div>
    <hr class="featurette-divider">

   <div class="row featurette align-items-center mb-4">
    <div class="col-md-6 order-md-2">
     <h2 class="featurette-heading">Design Bias Within Algorithms. <span class="text-muted">How computers become biased.</span></h2>
     <p class="lead">If the data used to 'teach' the algorithm has biases within it, the algorithm will inherit those biases and use them in it's decision-making.The more biased the inputs into an algorithm are, the more biased the algorithm becomes. Left unchecked, it will become more biased as it recognises it's own patterns. Find out more about AI biases <a href="https://research.aimultiple.com/ai-bias/">here.</a></p>
    </div>
      <div class="col-md-6 order-md-1">
        <img class="img-thumbnail" src=static/images/thumbsup_img.jpeg alt="Resume" width="600" height="400">
      </div>  
   </div>
   <hr class="featurette-divider">
   <div class="row featurette align-items-center mb-4">
    <div class="col-md-6">
    <h2 class="featurette-heading">What this means for you. <span class="text-muted">How the two come together.</span></h2>
    <p class="lead"> Resume writing has become more about convincing a machine that you are worth hiring than a manager. This means that focusing on key word selection is more important than ever. Find out how to write your resumes to convince applicant tracking systems <a href="/tips">here.</a></p>
    </div>
    <div class="col-md-6">
     <img class ="img-thumbnail" src=static/images/resume_img.jpeg alt="Resume" width="600" height="400">
    </div>
   </div>
{% endblock %}

website/templates/base.html
<!-- This is the base template that all other pages are created from-->
<!-- Importing code from macros.html to improve the navbar-->
{% from "macros.html" import nav_link with context %}
<html>
    <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    <title>Home</title>
    <link href="headers.css" rel="stylesheet">
    <link href="heroes.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link href="carousel.css" rel="stylesheet">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/style.css') }}">   
<!-- Creating the navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbartoggler" aria-controls="navbartoggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbartoggler">
         <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
          <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
          <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
        </svg>
        <ul class="nav navbar-nav me-auto mb-2 mb-lg-0">
                {{ nav_link('main.home', 'Home') }}
                {{ nav_link('main.about', 'About') }}
                {{ nav_link('main.upload', 'Resume Checker') }}
                {{ nav_link('main.tips', 'Tips') }}
        </ul>
        <!-- Displaying links relative to the user's login status-->
        {% if current_user.is_authenticated %}
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
          <a class="nav-item nav-link disabled text-muted px-3" href="#"><span>Welcome, {{ current_user.name
          }}</span></a>
          <a class="nav-item nav-link navtext px-3" href="{{ url_for('main.profile', user_id=current_user.user_id) }}">Profile</a>
          <a class="nav-item nav-link navtext px-3" href="{{ url_for('auth.logout') }}">Log Out</a>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
          <a class="nav-item nav-link navtext px-3" href="{{ url_for('auth.register') }}">Register</a>
           <a class="nav-item nav-link navtext px-3" href="{{ url_for('auth.login') }}">Log In</a>
        </ul>
        {% endif %}
        </div>
    </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} <!-- check if there are any messages -->
    <div class="container-fluid">
        <div class="row mt-3 mb-3">
        <div class="col-md-12">
        {% for category, message in messages %} 
            <!--loop through the messages-->
            <div class="alert alert-{{category}}">{{ message }}</div> 
            <!--display as alert-->
        {% endfor %}
        </div>
    </div>
    </div>
  
    {% endif %}
    {% endwith %}
    {% block header %}
    {% endblock %}
</head>
<body>
    {%block content %}
    {% endblock %}


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

website/templates/compare.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}
<main>
  <div class="container-fluid">
      <div class="row">
        <div class="px-4 py-0 my-5 text-center justify-content-center">
            <h1 class="display-5 fw-bold">Compare Results</h1>
            <div class="col-lg-6 mx-auto row justify-content-center">
              <p class="lead mb-4">Compare these two attempts.</p>
            </div>
          </div>
      </div>
	</div>
  <div class="wrapper container-fluid">
  <div class="row justify-content-center">
	<div class="card col-md-10">
	  <p>The values for each keyword indicate the weight they are assigned by the algorithm. The higher the weight, the better your resume is ranked in comparison to the dataset used to construct the model. Lower ranked keywords instead lower your score. A higher rank means your resume is more likely to be whitelisted by the algorithm and looked favourably on by the employer.</p>
    </div>
	</div>
  <div class="row">
  <div class="col-md-5 container-fluid">
      <div class="row justify-content-left">
        <div class="card mt-2">
          <div class="card-body">
            <h1 class="card-title">{{ average }}</h1>
            {% if average > 40 %}
            <h2 class="card-subtitle mb-2 text-info">Great!</h2>
			<p>This resume performed incredibly well. It is very likely to succeed automated resume vetting.</p>
			{% elif average > 25 %}
            <h2 class="card-subtitle mb-2 text-success">Good</h2>
			<p>This resume performed well. It is likely to succeed automated resume vetting.</p>
			{% elif average > 15 %}
            <h2 class="card-subtitle mb-2 text-warning">Average</h2>
			<p>This resume got a middling score and may or may not pass. Consider visiting the <a href="/tips">Tips Page</a> to see how you can improve your score, and try and get it over the line.</p>
			{% else %}
            <h2 class="card-subtitle mb-2 text-danger">Fail</h2>
			<p>This resume did not perform very well. Consider visiting the <a href="/tips">Tips Page</a> to see how you can improve your score.</p>
			{% endif %}
			
			{% if 1 in tip_values  %}
			<small class="text-danger">This resume has several keywords with low values, bringing down it's overall score - consider modifying or removing them.</small><br/>
			{% endif %}
			{% if 2 in tip_values %}
			<small class="text-danger">This resume has at least one keyword with a very low value, consider modifying or removing it.</small><br/>
			{% endif %}
			{% if 3 in tip_values %}
			<small class="text-warning">This resume has a few keywords with moderate values, consider utilising them more throughout the resume to increase their relevance and improve score.</small><br/>
			{% endif %}
			{% if 3 in tip_values %}
			<small class="text-success">This resume has at least one keyword with a very high score - this is improving its overall rating.</small><br/>
			{% endif %}
          </div>

		  <div class="row justify-content-center">
			<div id="chart" class="chart"></div>
		  </div>
		</div>
	   </div>
	</div>
	
	<div class="col-md-5 container-fluid">
      <div class="row justify-content-right">
        <div class="card mt-2">
          <div class="card-body">
            <h1 class="card-title">{{ compAverage }}</h1>
            {% if compAverage > 40 %}
            <h2 class="card-subtitle mb-2 text-info">Great!</h2>
			<p>This resume performed incredibly well. It is very likely to succeed automated resume vetting.</p>
			{% elif compAverage > 25 %}
            <h2 class="card-subtitle mb-2 text-success">Good</h2>
			<p>This resume performed well. It is likely to succeed automated resume vetting.</p>
			{% elif compAverage > 15 %}
            <h2 class="card-subtitle mb-2 text-warning">Average</h2>
			<p>This resume got a middling score and may or may not pass. Consider visiting the <a href="/tips">Tips Page</a> to see how you can improve your score, and try and get it over the line.</p>
			{% else %}
            <h2 class="card-subtitle mb-2 text-danger">Fail</h2>
			<p>This resume did not perform very well. Consider visiting the <a href="/tips">Tips Page</a> to see how you can improve your score.</p>
			{% endif %}
			
			{% if 1 in comp_tip_values  %}
			<small class="text-danger">This resume has several keywords with low values, bringing down it's overall score - consider modifying or removing them.</small><br/>
			{% endif %}
			{% if 2 in comp_tip_values %}
			<small class="text-danger">This resume has at least one keyword with a very low value, consider modifying or removing it.</small><br/>
			{% endif %}
			{% if 3 in comp_tip_values %}
			<small class="text-warning">This resume has a few keywords with moderate values, consider utilising them more throughout the resume to increase their relevance and improve score.</small><br/>
			{% endif %}
			{% if 3 in comp_tip_values %}
			<small class="text-success">This resume has at least one keyword with a very high score - this is improving its overall rating.</small><br/>
			{% endif %}
          </div>

		  <div class="row justify-content-center">
			<div id="comp_chart" class="comp_chart"></div>
		  </div>
		</div>
	   </div>
	  </div>
	</div>
  </div>
  
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script type="text/javascript">
    var graphs = {{graphJSON | safe}};
    Plotly.plot("chart", graphs, {});
	
	var compGraphs = {{compGraphJSON | safe}};
    Plotly.plot("comp_chart", compGraphs, {});
</script>

{% endblock %}

website/templates/index.html
<!-- Creating the home page -->
{% extends 'base.html' %}

{% block header %}
{% endblock %}


{% block content %}
        <div class="px-4 py-0 my-5 text-center">
         <h1 class="display-5 fw-bold">Resume Checker</h1>
        <div class="col-lg-6 mx-auto row justify-content-center">
          <p class="lead mb-4">Welcome to the resume checker. Here you can test your resume against a hiring algorithm.</p>
        </div>


        <div class="container marketing">
          <div class="row justify-content-center">
            <div class="col-lg-4 mb-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="140" height="140" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
              </svg>
              <h2>Upload a Resume</h2>
              <p>Upload a resume here to test it's strength against an applicant tracking system.</p>
              <p><a class="btn btn-secondary" href="/upload">Upload here &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="140" height="140" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
              </svg>
      
              <h2>View Resume Writing Tips</h2>
              <p>View tips to imrpove your resume writing skills to get that job you always wanted.</p>
              <p><a class="btn btn-secondary" href="/tips">View tips here &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <hr class="featurette-divider">
  
            <div class="row featurette align-items-center mb-4">
             <div class="col-md-6">
             <h2 class="featurette-heading">Resume Checking. <span class="text-muted">Rating your resume's strength.</span></h2>
             <p class="lead">By running your resume through an open-source applicant tracking system, we can show you exactly how strong your resume is.</p>
             </div>
             <div class="col-md-6">
              <img class ="img-thumbnail" src=static/images/resume_img.jpeg alt="Resume" width="600" height="400">
  
             </div>
            </div>
            <hr class="featurette-divider">
  
          <div class="row featurette align-items-center mb-4">
          <div class="col-md-6 order-md-2">
            <h2 class="featurette-heading">Resume Writing Tips. <span   class="text-muted">Improve your resume writing skills.</span></h2>
            <p class="lead">Using our tips page, you can take your resume to the next level with informed decision-making.</p>
          </div>
         <div class="col-md-6 order-md-1">
          <img class="img-thumbnail" src=static/images/thumbsup_img.jpeg alt="Resume" width="600" height="400">
  
          </div>
        </div>
{% endblock %}

website/templates/macros.html
<!-- Automates the creation of navbar links-->
{% macro nav_link(endpoint, name) %}
{% if request.endpoint.endswith(endpoint) %}
  <li class="nav-item active"><a class=nav-link href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% else %}
  <li class="nav-item"><a class=nav-link href="{{ url_for(endpoint) }}">{{name}}</a></li>
{% endif %}
{% endmacro %}

website/templates/profile.html
<!-- Creating the profile page -->
{% extends 'base.html' %}

{% block header %}
    <!-- Creating the user name and avatar segment-->
    <div class="row featurette align-items-center mb-4 justify-content-center">
        <div class="row container col-md-4 pl-5 justify-content-center">
            <div class="col-md-4">
                <img src="{{ user.avatar(128) }}">
               </div>
            <div class="col-md-6">
                <h1>User: {{ user.name }}</h1>
            </div>
        </div>
    </div>
    <!-- Creating their basic information segment-->
    <div class="row featurette align-items-center mb-4 justify-content-center">
        <div class="row container col-md-4 pl-5">
            <div class="col-md-4">
                <h2>Gender: {{user.gender }}</h2>
            </div>
            <div class="col-md-4">
                <h2>Date of Birth: {{user.birthdate }}</h2>
            </div>
            <div class="col-md-4">
                <h2>Area of Expertise: {{user.area_of_expertise }}</h2>
            </div>
        </div>
    </div>

        

    
            
{% endblock %}

{% block content %}
<!-- Loading a list of the user's resumes-->
    <div class="row featurette align-items-center justify-content-center">
        <div class="row container col-md-3 pl-5 justify-content-center">
            <h3>Below are your resumes.</h3>
			<div class="modal-footer compToggle">
			  <button type="button" class="btn btn-primary" onclick="ToggleCompare()">Compare Results</button>
			</div>
			<div class="modal-footer compToggle" style="display: none;">
			  <button type="button" class="btn btn-secondary" onclick="ToggleCompare()">Cancel</button>
			  <button id="compBtn" type="button" class="btn btn-primary" onclick="GetSelected()">Compare</button>
			</div>
        </div>
    </div>
    {% for resume in resume %}
        <div class="row align-items-center justify-content-center">
            <div id="card" class="card col-md-3 mb-0 mt-1">
				<h6 id="idStr" class="card-text">ID: {{ resume.resume_id }}</h4>
                <h4 class="card-title">{{ resume.resumename }}</h4>
                <h5 class="card-text card-overflow">Expertise: {{ resume.area_of_expertise }}</h5>
                <a href="{{ url_for('main.resume',user_id=user.user_id,resume_id=resume.resume_id) }}" class="stretched-link"></a>
				{% for resumelog in resumelog %}
				{% if resumelog.resume_id == resume.resume_id %}
				<h5 class="card-text card-overflow">Score: {{ resumelog.result }}</h4>
				{% endif %}
				{% endfor %}
              </div>
			<div class="col-md-1">
			  <input type="checkbox" class="check compToggle" style="display: none;"/>
            </div>
          </div>
    {% endfor %}
	
<script type="text/javascript">
	var checks = document.querySelectorAll(".compToggle");
	var max = 2;
	for (var i = 0; i < checks.length; i++)
	  checks[i].onclick = selectiveCheck;
	function selectiveCheck (event) {
	  var checkedChecks = document.querySelectorAll(".check:checked");
	  if (checkedChecks.length >= max + 1)
		return false;
	  if (checkedChecks.length < max)
		document.getElementById("compBtn").disabled = true;
	  else
		document.getElementById("compBtn").disabled = false;
	}
	
	function GetSelected() {
		var checkedChecks = document.querySelectorAll(".check:checked");
		resumeID = checkedChecks[0].parentNode.parentNode.children.namedItem("card").children.namedItem("idStr").innerHTML.substring(4)
		compareID = checkedChecks[1].parentNode.parentNode.children.namedItem("card").children.namedItem("idStr").innerHTML.substring(4)
		window.location = "/compare/" + resumeID + "/" + compareID;
	}
	
	function ToggleCompare() {
	  displayValue = "";
	  for (var i = 0; i < checks.length; i++) {
	    if (checks[i].style.display == "")
			displayValue = "none";
		else if (checks[i].style.display == "none")
			displayValue = "";
		checks[i].style.display = displayValue;
	  }
	}
</script>
{% endblock %}

website/templates/resume.html
<!-- Creating the resume page -->
{% extends 'base.html' %}

{% block header %}
<div class="row featurette align-items-center mb-1 justify-content-center">
    <div class="row container col-md-3 pl-5 justify-content-center">
        <h1>{{resume.resumename}}</h1>
    </div>
</div>
<hr>    
<div class="row featurette align-items-center mb-4 justify-content-center">
    <div class="row container col-md-3 pl-5 justify-content-center">
        <h3>Uploaded by {{user.name}}</h3>
    </div>
	<div class="row container col-md-3 pl-5 justify-content-center">
        <a type="button" class="btn btn-primary" href="/results/{{user.user_id}}/{{resume.resume_id}}">View Results</a>
    </div>
</div>

{% endblock %}

{% block content %}
<div class="row featurette align-items-center mb-4 justify-content-center">
    <div class="row container col-md-6 pl-5 justify-content-center">
        <iframe src='/{{resume.resumecontents}}' width="800px" height="2100px" type="application/pdf"></iframe>
    </div>
</div>
    
{% endblock %}

website/templates/upload.html
<!-- Creating the upload page-->
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}
      <div class="px-4 py-0 my-5 text-center justify-content-center">
        <h1 class="display-5 pb-5 fw-bold">Resume Checker</h1>
        <div class="col-lg-6 mx-auto row justify-content-center">
          <form action="/upload" method='POST' enctype='multipart/form-data'>
            <!-- Allowing users to select the profession their resume is for-->
            <div class="col-md-4 offset-md-4">
              <select name ='expertise'>
                <option selected>Choose your profession</option>
                <option value="IT">IT</option>
                <option value="Retail">Retail</option>
                <option value="Management">Management</option>
                <option value="Finance">Finance</option>
                <option value="Education">Education</option>
                <option value="Hospitality">Hospitality</option>
              </select>
            </div> 
            <!-- Allowing the user to upload their resume-->
            <label class="custom-file-label pt-3" for ='resume'>Select Resume</label>
            <div class="custom-file pt-3 mb-3 col-md-6 offset-md-4">
              <input type="file" class="custom-file-input" id="resume" name='resume' accept=".pdf">
            </div>
            <button type='submit' class='btn btn-secondary'>Upload Resume</button>
          </form>
        </div>
{% endblock %}

website/templates/user.html
<!-- Creating the login and registration page-->
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}


<!-- Display either login or registration page-->
<div class="container-fluid">
    <div class="page-header col-md-4 mx-auto ml-5 text-center">
        <h4>{{heading}}</h4>
    </div>

    <div class="col-md-4 mx-auto ml-5">
    {{wtf.quick_form(form)}}
    </div>

    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower =='login' %}
    <div class="col-md-4 mb-5 mx-auto ml-5">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}
</div>
{% endblock %}